id: P006664
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:14:22.331381
source_metadata:
  id: bdr:W1KG22267
  title: འདུལ་བ་རྒྱ་མཚོའི་སྙིང་པོའི་དོན་ཕྱོགས་གཅིག་ཏུ་བསྡུས་ནས་སྟོན་པ་བློ་གསལ་མཁས་པའི་མགུལ་རྒྱན་མུ་ཏིག་གི་ཕྲེང་བ།
  author: ''
  volumes:
    3978abad167e4021b0fb49e774c6baa9:
      image_group_id: I1KG22311
      title: ''
      volume_number: 1
      total_pages: 348
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
