id: P006664
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22267
  title: འདུལ་བ་རྒྱ་མཚོའི་སྙིང་པོའི་དོན་ཕྱོགས་གཅིག་ཏུ་བསྡུས་ནས་སྟོན་པ་བློ་གསལ་མཁས་པའི་མགུལ་རྒྱན་མུ་ཏིག་གི་ཕྲེང་བ།
  author: ''
  volumes:
    3978abad167e4021b0fb49e774c6baa9:
      image_group_id: I1KG22311
      title: ''
      volume_number: 1
      total_pages: 348
      base_file: v001.txt
